[pytest]
addopts = -p no:cacheprovider --basetemp=tests/.pytest_runtime/basetemp
cache_dir = tests/.pytest_runtime/cache
testpaths = tests
norecursedirs = data pytest-cache-files-* tests/.pytest_runtime tests/.pytest_tmp tests/.pytest_cache tests/tmpdir